version: "2"
services: 
  nginx:
    image: nginx:stable-alpine
    ports: 
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
  node-app:
    build: .
    environment: 
      - POST=3000
    depends_on: 
      - mongo


  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=61Faucet
    volumes: 
      - mongo-db:/data/db  
  redis:
    image: redis  
  
volumes: 
    mongo-db:      

  